import {
  library,
} from '@fortawesome/fontawesome-svg-core'
import {
  faAngleLeft,
  faAngleRight,
  faCalendar,
  faCaretDown,
  faCaretUp,
  faCheck,
  faEnvelope,
  faExclamationCircle,
  faExclamationTriangle,
  faEye,
  faImages,
  faInfoCircle,
  faMusic,
  faPhone,
  faPlus,
  faRetweet,
  faSearch,
  faSyncAlt,
  faTag,
  faTimes,
  faTimesCircle,
  faTrash,
  faUpload,
  faUser,
  faUserLock,
  faUserPlus,
  faVideo,
} from '@fortawesome/free-solid-svg-icons'
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'
library.add(
  faCalendar,
  faUserLock,
  faUserPlus,
  faImages,
  faMusic,
  faInfoCircle,
  faRetweet,
  faVideo,
  faSyncAlt,
  faTimes,
  faTag,
  faAngleLeft,
  faAngleRight,
  faUpload,
  faExclamationCircle,
  faCheck,
  faExclamationTriangle,
  faPlus,
  faTrash,
  faPhone,
  faUser,
  faEye,
  faEnvelope,
  faTimesCircle,
  faSearch,
  faCaretDown,
  faCaretUp,
)

export default FontAwesomeIcon
